### PR TITLE
Added new features

### PR DESCRIPTION
**Pull request by priyagupta20044**
1. Added dark theme with the help of a new gear icon on the top left with proper margin. Added a new Javascript file that handles the toggle operation for light and dark theme. 
2. Added a profile picture option with a flip card along with introductory texts (can be modified as per will) with shadow and borders 
3. Added smooth transition effects when clicked on the content of navbar by adding smooth scroll 
4. Aligned the introduction text to justify for better look 

Attached a video for the reference 

https://github.com/user-attachments/assets/86e510bb-e84f-4ad7-90a2-c5416c648f79
solves #8

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Great ! But you can enhance it more.
Add option resume in navbar
And remove the flip transition change it.
Make the portfolio look modern. Or you add another portfolio if you have

**Comment by priyagupta20044** [comment]
sure, working on it

**Comment by Ayu-hack** [comment]
Replace MyApp with some name or logo

**Comment by Ayu-hack** [comment]
YOU ARE WORKING ON IT OR NOT ?

**Comment by priyagupta20044** [comment]
I need more time, I had completed the previous changes but having continuous exams so I would be requiring time to incorporating changes that you requested the other day.

**Comment by Ayu-hack** [comment]
okay. Take your time!

**Comment by Ayu-hack** [comment]
you are working or I should close

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Pull request merged**
