### PR TITLE
add contact-us feature

### PR DESCRIPTION
**Pull request by ridholess**
please add "hacktoberfest-accepted" label

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please star n fork

**Comment by ridholess** [comment]
I've did it, star & fork. please add "hacktoberfest-accepted" label

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)

**Pull request merged**
